import os
from datetime import datetime
from fpdf import FPDF

class ReportGenerator:
    def __init__(self, target_url, visited_urls, scan_settings, screenshots=None, output_dir="reports"):
        self.target_url = target_url
        self.visited_urls = visited_urls
        self.scan_settings = scan_settings
        self.enable_form_detection = scan_settings.get("form_detection", False)
        self.enable_dirsearch = scan_settings.get("dirsearch", False)
        self.screenshots = screenshots or []
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def generate_pdf(self):
        report_file = os.path.join(self.output_dir, f"ReconX_Report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf")
        pdf = FPDF()
        pdf.add_page()
        pdf.set_font("Arial", "B", 16)
        pdf.cell(0, 10, f"ReconX Report - {self.target_url}", ln=True)

        pdf.set_font("Arial", "", 12)
        pdf.cell(0, 10, f"Scan Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True)
        
        pdf.set_font("Arial", '', 12)
        pdf.cell(0, 6, "Features Enabled:", ln=True)
        features = []
        if self.enable_form_detection:
            features.append("Form Detection")
        if self.enable_dirsearch:
            features.append("Directory Bruteforcing")
        # Add more features as needed
        if features:
            for f in features:
                pdf.cell(0, 6, f"- {f}", ln=True)
        else:
            pdf.cell(0, 6, "None", ln=True)


        pdf.set_font("Arial", "B", 14)
        pdf.cell(0, 10, "Crawled URLs:", ln=True)
        pdf.set_font("Arial", "", 11)
        for url in list(self.visited_urls)[:50]:
            pdf.set_text_color(0, 0, 255)  # Blue color for links
            pdf.cell(0, 6, str(url), ln=True, link=str(url))

        if len(self.visited_urls) > 50:
            pdf.cell(0, 6, f"...and {len(self.visited_urls)-50} more URLs.", ln=True)

        if self.screenshots:
            pdf.add_page()
            pdf.set_font("Arial", "B", 14)
            pdf.cell(0, 10, "Captured Screenshots:", ln=True)
            for img_path in self.screenshots[:5]:
                try:
                    pdf.image(img_path, w=120)
                    pdf.ln(10)
                except RuntimeError:
                    pdf.cell(0, 10, f"Error displaying {img_path}", ln=True)

        pdf.set_font("Arial", "B", 14)
        pdf.cell(0, 10, "Scan Configuration:", ln=True)
        pdf.set_font("Arial", "", 11)
        for k, v in self.scan_settings.items():
            pdf.cell(0, 6, f"{k}: {v}", ln=True)



        pdf.add_page()
        pdf.set_font("Arial", 'I', 11)
        pdf.cell(0, 10, f"Total URLs Crawled: {len(self.visited_urls)}", ln=True)
        pdf.cell(0, 10, "Generated by ReconX - Automated Reconnaissance Tool", ln=True)


        pdf.output(report_file)
        print(f"[✓] PDF Report generated: {report_file}")
        return report_file